version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres


volumes:
  postgres: