---
title: EscAPI Preparation domain
---
classDiagram
  namespace preparation {
    class Player {
      take(inventory, item)
      empty()
      lookInBackpack() Item[]
      lookMap(dungeonMap) Dungeon[]
    }

    class Backpack {
      open() Item[]
      add(Item)
      remove(Item)
    }

    class Camp {
      items Item[]
    }

    class DungeonsMap {
      dungeons Dungeon[]
    }

    class Dungeon {
      name
      description
    }

    class Item {
      name
      description
    }
  }

Player --* Backpack
