---
title: EscAPI Preparation domain
---
classDiagram
  namespace preparation {
    class Player {
      take(inventory, item)
      empty()
      lookInBackpack() Item[]
      lookMap(adventureMap) Adventure[]
    }

    class Backpack {
      open() Item[]
      add(Item)
      remove(Item)
    }

    class Camp {
      items Item[]
    }

    class AdventuresMap {
      adventures Adventure[]
    }

    class Adventure {
      name
      description
    }

    class Item {
      name
      description
    }
  }

Player --* Backpack
